# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de03a69d6c57aab49a4f8d35edc24bd928ef6c4e99b284b05e4e215028f10f4a834137a4cd8975de981c6db4865f2ece8ca52a529586bfcfed679ea8a51b8b1b

test:
  secret_key_base: 524a03e1bc202d8b20ff6fac51c538fc1f897a9a5c21b69a2d87458a63c8405220b6c98e74628655685c25a201cfd8b5c274ed9fe3a0fda53d21357f932fefeb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
